
import pandas as pd
import os

data = [
   
    ("Pizza Hut", "Food & Dining"), ("Dominos pizza", "Food & Dining"),
    ("McDonald's burger", "Food & Dining"), ("KFC chicken", "Food & Dining"),
    ("Zomato order", "Food & Dining"), ("Swiggy delivery", "Food & Dining"),
    ("lunch at cafe", "Food & Dining"), ("dinner restaurant", "Food & Dining"),
    ("breakfast hotel", "Food & Dining"), ("grocery store", "Food & Dining"),
    ("Big Basket vegetables", "Food & Dining"), ("Blinkit groceries", "Food & Dining"),
    ("coffee shop", "Food & Dining"), ("Starbucks coffee", "Food & Dining"),
    ("milk bread eggs", "Food & Dining"), ("biryani order", "Food & Dining"),
    ("snacks evening", "Food & Dining"), ("fruit market", "Food & Dining"),
    ("bakery cake", "Food & Dining"), ("ice cream parlour", "Food & Dining"),
    ("chai samosa", "Food & Dining"), ("dabba meal", "Food & Dining"),
    ("Subway sandwich", "Food & Dining"), ("Burger King", "Food & Dining"),
    ("food delivery", "Food & Dining"), ("restaurant bill", "Food & Dining"),
    ("canteen lunch", "Food & Dining"), ("tiffin box", "Food & Dining"),
    ("Zepto groceries", "Food & Dining"), ("Dunzo groceries", "Food & Dining"),
    ("vegetable market", "Food & Dining"), ("chicken mutton", "Food & Dining"),
    ("fish market", "Food & Dining"), ("Chinese food", "Food & Dining"),
    ("south indian food", "Food & Dining"), ("north indian thali", "Food & Dining"),
    ("buffet dinner", "Food & Dining"), ("birthday cake", "Food & Dining"),
    ("party food order", "Food & Dining"), ("office lunch", "Food & Dining"),
    ("vada pav", "Food & Dining"), ("dosa idli", "Food & Dining"),
    ("pani puri chaat", "Food & Dining"), ("sweet shop mithai", "Food & Dining"),
    ("dry fruits nuts", "Food & Dining"), ("juice bar", "Food & Dining"),
    ("smoothie protein shake", "Food & Dining"), ("maggi noodles", "Food & Dining"),
    ("ready meals packet", "Food & Dining"), ("cooking oil rice dal", "Food & Dining"),
    ("paneer tofu", "Food & Dining"), ("mineral water", "Food & Dining"),
    ("cold drink beverages", "Food & Dining"), ("tea coffee powder", "Food & Dining"),
    ("spices masala", "Food & Dining"), ("cheese butter", "Food & Dining"),
    ("Haldirams snacks", "Food & Dining"), ("Lay's chips biscuits", "Food & Dining"),
    ("hotel breakfast", "Food & Dining"), ("mess food", "Food & Dining"),

    
    ("Uber ride", "Transportation"), ("Ola cab", "Transportation"),
    ("Rapido bike", "Transportation"), ("auto rickshaw", "Transportation"),
    ("metro card recharge", "Transportation"), ("bus ticket", "Transportation"),
    ("train ticket", "Transportation"), ("petrol fuel", "Transportation"),
    ("diesel refill", "Transportation"), ("parking charges", "Transportation"),
    ("toll tax highway", "Transportation"), ("vehicle service", "Transportation"),
    ("car maintenance", "Transportation"), ("bike repair", "Transportation"),
    ("cab booking", "Transportation"), ("taxi fare", "Transportation"),
    ("rickshaw fare", "Transportation"), ("IRCTC ticket", "Transportation"),
    ("local train pass", "Transportation"), ("fuel pump", "Transportation"),
    ("Uber Eats delivery", "Transportation"), ("InDrive cab", "Transportation"),
    ("Meru taxi", "Transportation"), ("BluSmart cab", "Transportation"),
    ("monthly bus pass", "Transportation"), ("two wheeler fuel", "Transportation"),
    ("car insurance", "Transportation"), ("bike insurance", "Transportation"),
    ("vehicle registration", "Transportation"), ("driving license fees", "Transportation"),
    ("CNG gas vehicle", "Transportation"), ("EV charging", "Transportation"),
    ("tyre puncture repair", "Transportation"), ("oil change car", "Transportation"),
    ("car wash", "Transportation"), ("helmet purchase", "Transportation"),
    ("traffic challan fine", "Transportation"), ("fastag recharge", "Transportation"),
    ("airport cab", "Transportation"), ("station to home cab", "Transportation"),
    ("office commute", "Transportation"), ("school bus fees", "Transportation"),
    ("inter city bus", "Transportation"), ("state transport bus", "Transportation"),
    ("share auto", "Transportation"), ("electric scooter ride", "Transportation"),
    ("Yulu cycle rental", "Transportation"), ("Bounce scooter", "Transportation"),
    ("parking token", "Transportation"), ("road tax", "Transportation"),

    
    ("Amazon purchase", "Shopping"), ("Flipkart order", "Shopping"),
    ("Meesho order", "Shopping"), ("Myntra clothes", "Shopping"),
    ("shoes purchase", "Shopping"), ("shirt jeans", "Shopping"),
    ("dress kurti", "Shopping"), ("electronics gadget", "Shopping"),
    ("mobile phone", "Shopping"), ("headphones earphones", "Shopping"),
    ("laptop bag", "Shopping"), ("online shopping", "Shopping"),
    ("gift purchase", "Shopping"), ("home decor", "Shopping"),
    ("kitchenware vessel", "Shopping"), ("furniture chair", "Shopping"),
    ("stationery pen notebook", "Shopping"), ("cosmetics makeup", "Shopping"),
    ("watch purchase", "Shopping"), ("sunglasses buy", "Shopping"),
    ("Nykaa beauty", "Shopping"), ("Ajio fashion", "Shopping"),
    ("Snapdeal order", "Shopping"), ("Tata Cliq", "Shopping"),
    ("saree blouse", "Shopping"), ("suit blazer", "Shopping"),
    ("kids clothes toys", "Shopping"), ("handbag purse", "Shopping"),
    ("wallet belt", "Shopping"), ("perfume deodorant", "Shopping"),
    ("face cream lotion", "Shopping"), ("shampoo conditioner", "Shopping"),
    ("toothbrush toothpaste", "Shopping"), ("soap body wash", "Shopping"),
    ("TV television", "Shopping"), ("refrigerator washing machine", "Shopping"),
    ("microwave oven", "Shopping"), ("air conditioner", "Shopping"),
    ("water purifier", "Shopping"), ("air purifier", "Shopping"),
    ("bedsheet pillow", "Shopping"), ("curtains blinds", "Shopping"),
    ("plant pot garden", "Shopping"), ("tool hardware", "Shopping"),
    ("stationery office supply", "Shopping"), ("printer ink", "Shopping"),
    ("camera photography", "Shopping"), ("gaming mouse keyboard", "Shopping"),
    ("charger cable wire", "Shopping"), ("power bank", "Shopping"),

    
    ("Netflix subscription", "Entertainment"), ("Amazon Prime", "Entertainment"),
    ("Hotstar Disney", "Entertainment"), ("Spotify music", "Entertainment"),
    ("YouTube Premium", "Entertainment"), ("movie tickets", "Entertainment"),
    ("PVR cinemas", "Entertainment"), ("concert tickets", "Entertainment"),
    ("gaming purchase", "Entertainment"), ("PlayStation game", "Entertainment"),
    ("bowling alley", "Entertainment"), ("theme park entry", "Entertainment"),
    ("amusement park", "Entertainment"), ("cricket match tickets", "Entertainment"),
    ("OTT streaming", "Entertainment"), ("fiction book", "Entertainment"),
    ("comic books", "Entertainment"), ("video game Steam", "Entertainment"),
    ("INOX multiplex", "Entertainment"), ("fun zone arcade", "Entertainment"),
    ("escape room", "Entertainment"), ("laser tag", "Entertainment"),
    ("swimming pool entry", "Entertainment"), ("zoo aquarium", "Entertainment"),
    ("museum entry", "Entertainment"), ("SonyLIV subscription", "Entertainment"),
    ("Zee5 subscription", "Entertainment"), ("MX Player premium", "Entertainment"),
    ("Apple TV plus", "Entertainment"), ("Google Play movies", "Entertainment"),
    ("Xbox Game Pass", "Entertainment"), ("Nintendo game", "Entertainment"),
    ("board game purchase", "Entertainment"), ("playing cards games", "Entertainment"),
    ("karaoke night", "Entertainment"), ("stand up comedy", "Entertainment"),
    ("live music concert", "Entertainment"), ("cultural event", "Entertainment"),
    ("sports event ticket", "Entertainment"), ("IPL ticket", "Entertainment"),
    ("badminton court booking", "Entertainment"), ("tennis court fees", "Entertainment"),
    ("billiards snooker", "Entertainment"), ("go karting", "Entertainment"),
    ("trampoline park", "Entertainment"),

    
    ("electricity bill", "Bills & Utilities"), ("water bill", "Bills & Utilities"),
    ("gas cylinder", "Bills & Utilities"), ("internet recharge", "Bills & Utilities"),
    ("broadband bill", "Bills & Utilities"), ("mobile recharge", "Bills & Utilities"),
    ("DTH recharge", "Bills & Utilities"), ("rent payment", "Bills & Utilities"),
    ("maintenance charges", "Bills & Utilities"), ("society fees", "Bills & Utilities"),
    ("insurance premium", "Bills & Utilities"), ("loan EMI", "Bills & Utilities"),
    ("credit card payment", "Bills & Utilities"), ("telephone bill", "Bills & Utilities"),
    ("wifi bill", "Bills & Utilities"), ("house rent", "Bills & Utilities"),
    ("postpaid bill", "Bills & Utilities"), ("Jio recharge", "Bills & Utilities"),
    ("Airtel prepaid", "Bills & Utilities"), ("Vi Vodafone recharge", "Bills & Utilities"),
    ("BSNL bill", "Bills & Utilities"), ("Tata Sky DTH", "Bills & Utilities"),
    ("Dish TV subscription", "Bills & Utilities"), ("home loan EMI", "Bills & Utilities"),
    ("car loan EMI", "Bills & Utilities"), ("personal loan EMI", "Bills & Utilities"),
    ("property tax", "Bills & Utilities"), ("municipal tax", "Bills & Utilities"),
    ("society maintenance", "Bills & Utilities"), ("building repair fund", "Bills & Utilities"),
    ("PG hostel rent", "Bills & Utilities"), ("dormitory fees", "Bills & Utilities"),
    ("co-working space rent", "Bills & Utilities"), ("office rent", "Bills & Utilities"),
    ("storage facility", "Bills & Utilities"), ("BESCOM electricity", "Bills & Utilities"),
    ("MSEDCL bill", "Bills & Utilities"), ("gas pipeline bill", "Bills & Utilities"),
    ("cooking gas piped", "Bills & Utilities"), ("water tanker charges", "Bills & Utilities"),
    ("cable TV charges", "Bills & Utilities"), ("home security subscription", "Bills & Utilities"),
    ("printer subscription", "Bills & Utilities"), ("software license", "Bills & Utilities"),
    ("cloud storage subscription", "Bills & Utilities"),

    
    ("doctor consultation", "Healthcare"), ("hospital charges", "Healthcare"),
    ("medicine pharmacy", "Healthcare"), ("medical test", "Healthcare"),
    ("blood test", "Healthcare"), ("X-ray scan", "Healthcare"),
    ("dentist fees", "Healthcare"), ("eye checkup", "Healthcare"),
    ("health checkup", "Healthcare"), ("gym membership", "Healthcare"),
    ("yoga class", "Healthcare"), ("physiotherapy", "Healthcare"),
    ("vaccination", "Healthcare"), ("tablet capsule", "Healthcare"),
    ("Apollo pharmacy", "Healthcare"), ("1mg medicine", "Healthcare"),
    ("NetMeds order", "Healthcare"), ("clinic fees", "Healthcare"),
    ("lab test report", "Healthcare"), ("MRI scan", "Healthcare"),
    ("CT scan", "Healthcare"), ("ultrasound", "Healthcare"),
    ("ECG test", "Healthcare"), ("surgery operation", "Healthcare"),
    ("ambulance charges", "Healthcare"), ("hospital admission", "Healthcare"),
    ("insulin medicine", "Healthcare"), ("BP sugar medicine", "Healthcare"),
    ("ortho knee pain", "Healthcare"), ("eye glasses spectacles", "Healthcare"),
    ("contact lenses", "Healthcare"), ("hearing aid", "Healthcare"),
    ("mental health therapy", "Healthcare"), ("psychiatrist fees", "Healthcare"),
    ("dermatologist skin", "Healthcare"), ("acne treatment", "Healthcare"),
    ("dietitian nutritionist", "Healthcare"), ("weight loss program", "Healthcare"),
    ("fitness trainer", "Healthcare"), ("CrossFit membership", "Healthcare"),
    ("zumba class", "Healthcare"), ("pilates class", "Healthcare"),
    ("protein supplement", "Healthcare"), ("vitamin supplement", "Healthcare"),
    ("ayurvedic treatment", "Healthcare"),

    
    ("college fees", "Education"), ("tuition fees", "Education"),
    ("Udemy course", "Education"), ("Coursera subscription", "Education"),
    ("books textbook", "Education"), ("exam fees", "Education"),
    ("coaching class", "Education"), ("library membership", "Education"),
    ("certification course", "Education"), ("workshop seminar", "Education"),
    ("skill development", "Education"), ("training program", "Education"),
    ("school fees", "Education"), ("university fees", "Education"),
    ("online learning", "Education"), ("edX course", "Education"),
    ("LinkedIn Learning", "Education"), ("Skillshare subscription", "Education"),
    ("Khan Academy", "Education"), ("BYJU's subscription", "Education"),
    ("Unacademy course", "Education"), ("Vedantu class", "Education"),
    ("IIT JEE coaching", "Education"), ("NEET coaching", "Education"),
    ("UPSC preparation", "Education"), ("IELTS TOEFL exam", "Education"),
    ("GRE GMAT fees", "Education"), ("language class", "Education"),
    ("spoken English", "Education"), ("music class lessons", "Education"),
    ("dance class", "Education"), ("art drawing class", "Education"),
    ("coding bootcamp", "Education"), ("data science course", "Education"),
    ("AWS certification", "Education"), ("MBA course fees", "Education"),
    ("distance learning", "Education"), ("study material", "Education"),
    ("notebook stationery", "Education"), ("drawing instruments", "Education"),

    
    ("flight ticket", "Travel"), ("IndiGo flight", "Travel"),
    ("Air India booking", "Travel"), ("hotel booking", "Travel"),
    ("OYO rooms", "Travel"), ("MakeMyTrip booking", "Travel"),
    ("Goibibo hotel", "Travel"), ("holiday trip", "Travel"),
    ("tour package", "Travel"), ("resort stay", "Travel"),
    ("travel insurance", "Travel"), ("visa fees", "Travel"),
    ("holiday vacation", "Travel"), ("sightseeing tour", "Travel"),
    ("travel bag luggage", "Travel"), ("SpiceJet ticket", "Travel"),
    ("Vistara flight", "Travel"), ("GoAir flight", "Travel"),
    ("Treebo hotel", "Travel"), ("Zostel hostel", "Travel"),
    ("Airbnb stay", "Travel"), ("backpacking trip", "Travel"),
    ("Goa trip", "Travel"), ("Manali trip", "Travel"),
    ("Kerala tour", "Travel"), ("Rajasthan tour", "Travel"),
    ("hill station trip", "Travel"), ("beach vacation", "Travel"),
    ("international flight", "Travel"), ("passport renewal", "Travel"),
    ("travel guide book", "Travel"), ("travel accessories", "Travel"),
    ("forex currency exchange", "Travel"), ("travel adapter", "Travel"),
    ("travel pillow", "Travel"), ("sunscreen travel", "Travel"),
    ("snorkeling scuba", "Travel"), ("trekking camping", "Travel"),
    ("adventure sports", "Travel"), ("cruise ship booking", "Travel"),

    
    ("ATM withdrawal", "Other"), ("bank charges", "Other"),
    ("miscellaneous expense", "Other"), ("donation charity", "Other"),
    ("temple donation", "Other"), ("newspaper subscription", "Other"),
    ("laundry cleaning", "Other"), ("haircut salon", "Other"),
    ("barber shop", "Other"), ("tailor stitching", "Other"),
    ("cash transfer", "Other"), ("personal expense", "Other"),
    ("lottery ticket", "Other"), ("pet food vet", "Other"),
    ("dog cat food", "Other"), ("pet grooming", "Other"),
    ("plant nursery", "Other"), ("gardening tools", "Other"),
    ("NGO donation", "Other"), ("PM relief fund", "Other"),
    ("political donation", "Other"), ("religious expense", "Other"),
    ("festive shopping", "Other"), ("pooja material", "Other"),
    ("festival gift", "Other"), ("greeting card gift wrap", "Other"),
    ("post office courier", "Other"), ("notary legal fees", "Other"),
    ("lawyer advocate", "Other"), ("CA chartered accountant", "Other"),
    ("income tax payment", "Other"), ("GST payment", "Other"),
    ("fine penalty", "Other"), ("lost item replacement", "Other"),
    ("emergency expense", "Other"),
]

df = pd.DataFrame(data, columns=["title", "category"])
os.makedirs("data", exist_ok=True)
df.to_csv("data/training_data.csv", index=False)

print(f"✅ Training data saved: {len(df)} samples")
print(f"\nCategory distribution:")
print(df["category"].value_counts())